russross/blackfriday

block.go

- It has moved into a smaller standalone repo.
- Closes #139.
Please review. Let's see if this is an improvement and how well it works. :)
I will give push rights to that repo to the maintainers of `blackfriday`. You trust me with push rights to this repo, so I see no reason not to the same. Of course, the idea is to stick to creating issues and pull requests and merging after getting a LGTM, but just in case.

Update import path of sanitized_anchor_name.

---

inline_test.go
smartypants.go

So that dates like 1/2/2005 and 2005/3/4 stay the way it is
without turning into ½/2005 and 2005/¾.
See http://discuss.gohugo.io/t/any-way-to-disable-smart-fractions/328
for discussions.

Avoid converting dates into fractions

---

LICENSE.txt
README.md

It's pretty standard to have a license file, and some projects require
them before your code can be used in their code.  Move the license to
its own file.

Move the license info from README to LICENSE file

---

block.go
markdown.go

Resolve #148 by remove unnecessary copy of input.
Here is the benchmark result:
BenchmarkFenceCode         20000             78546 ns/op
BenchmarkNoFenceCode       20000             77780 ns/op

Delete unnecessary copy of input when enable fenced code extension

---

html.go
inline_test.go

This adds a flag to add a `rel="noreferrer"` attribute to generated links. This is generally a good idea when rendering third-party HTML with the `HTML_HREF_TARGET_BLANK` flag. Otherwise the linked-to page can use `window.opener.location.replace('http://attacker.com')` to replace the URL of the original tab, which is a potential security vulnerability.
Tests have been added for this case. Thanks for making this awesome library!

add rel="noreferrer" option

---

inline.go
inline_test.go

The second footnote was treated as if the pair of them were a reference
style link, without checking if the second bit is another footnote.
Fixes issue #158.

Fix recognition of consecutive footnotes

---

inline.go
inline_test.go
markdown.go

Many don't like double space because it's not visible. For this, CommonMark and other dialects allow backslash hard line breaks. See http://spec.commonmark.org/0.18/#example-527
I added an extension (EXTENSION_BACKSLASH_LINE_BREAK), added by default in Common profile.
All tests pass.

Implement backslash hard line break extension

---

inline.go
inline_test.go
markdown.go

If a user provides a ReferenceOverride function, then reference ids
will be passed to the given ReferenceOverride function first, before
consulting the generated reference table.
The goal here is to enable programmable support for
"WikiWords"-style identifiers or other application-specific
user-generated keywords.
Example, writing documentation:
The [Frobnosticator][] is a very important class in our codebase.
While it is used to frobnosticate widgets in general, it can also
be passed to the [WeeDoodler][] to interesting effect.
This might be solveable with the HTML Renderer relative prefix, but
I didn't see a good way of making a short link to 'Frobnosticator'
relatively without having to write it twice. Maybe
'<Frobnosticator>' should work? Should Autolinks work for relative
links?
In …

Add programmable reference overrides

---

html.go
inline_test.go

- This changes HTML renderer not to always add a newline character after \<img\> tags. This is desirable because \<img\> tags can be inlined, and sometimes you want to avoid whitespace on left and right sides. Previous behavior of always adding a newline would unavoidably create whitespace after \<img\> tag.
- Update all tests to match new behavior. There are few changes, and they're completely isolated to inline image tests.
Fixes #169.
Change Overview
-------
Consider the following Markdown input:
```Markdown
Title
===
An inline image ![img](http://www.example.com/image.png) looks like that.
Another paragraph.
```
Previously, this would generate the following HTML output:
```HTML
<h1>Title</h1>
<p>An inline image <img src="http://www.example.com/image.png" alt="img" />
looks like …
```

Do not emit newline after <img> tag.

---

block.go
block_test.go
html.go
markdown.go

Hi,
This PR implements definition lists support as described [here](https://michelf.ca/projects/php-markdown/extra/#def-list).
This support is available as an extension using `EXTENSION_DEFINITION_LISTS`.
Hoping it will suits you.
King regards,
Vincent

Add definition lists extension support

---

inline.go
inline_test.go

First check for escaped character, *then* look if i-th character is an
emphasis character.
Closes #18.

Fix escaping asterisks within emphasis

---

inline.go
inline_test.go

Start searching for emphasis character at 0th index instead of 1st.
Fixes a corner case with doubly emphasised code span followed by
another code span on the same line.
Changes interpretation of improperly nested emphasis, hence the change
in TestEmphasisMix().
Closes #156.

Fix bug parsing emphasis

---

inline.go
inline_test.go

When parsing a deferred footnote, we already know it's a footnote from
the '[^' part, so we can use that to hit a proper switch branch
(default) a bit later on.
Closes #164.

Fix footnote followed by a reference style link

---

block.go
block_test.go
inline.go
inline_test.go

Added test cases both for inline and block workflows.
Closes #136.

Handle comments within a block

---

block.go
block_test.go
markdown.go

Improves fenced code block detection in paragraphs and blockquotes. Directly addresses #122, but refixes #45 along the way. More details in respective commit messages.

Fix issue 122: fenced code blocks inside blockquotes

---

inline_test.go
markdown.go

This is both nasty and neat at the same time. All the code could handle nested footnotes just fine, the only place that was not working was the final loop that printed the list. The loop was in a range form, which couldn't account for another footnote being inserted while processing existing ones. Changing the loop to the iterative form solves that.
Fixes #193.

Fix nested footnotes

---

inline.go
inline_test.go

Link parser interpreted the sequence "![^foo]" as an image, but if
footnote extension is enabled, it's quite clear that it should be
interpreted as a footnote following something with an exclamation point
at the end.
Closes #194.

Fix footnote following an exclamation point

---

README.md

A couple of months ago I created a custom renderer for blackfriday that converts markdown to vimdoc format, and was wondering if you can include it in your README.

Adding a link to Md2Vim.

---

inline.go
inline_test.go
markdown.go

Removed an early-out return statement that used to short circuit reference detection code if no trailing newline was present. Fixes #180.
Fixed some cosmetics along the way.

Fix for #180

---

block.go
block_test.go

This problem has been lurking since the very early days, apparently introduced with commit 583b3c5e. Strange that nobody stumbled upon it for so long.
Instead of swallowing an empty line and then reintroducing it back again in certain cases, collect the list item body in an unaltered form and let the recursive parsing call sort things out.
Fixes issue #228.

Fix bug with gathering list item lines

---

inline_test.go
markdown.go

The previous fix got reverted/removed by new commits.

Fix regession: index out of range panic in reference link (#172, #173)

---

.travis.yml
README.md

Also make tip a fast-finish allowed failure. That way, if CI fails on tip due to a temporary issue with tip, it will not break build status. However, it's still possible to see tip build status by looking at CI details page.
Do not run go vet with Go 1.4 or older since it's not included in the standard library, and it's no longer available in external standard library.
Add godoc badge to README.md.

Travis: Run gofmt -s, go vet, go test -race, add Go 1.6.

---

block.go
block_test.go

Prevent adjacent lists of differing types from being merged into a
single list.  No options are provided to enable the previous behavior.
Fixes #235

Fix adjacent list merging

---

block.go
block_test.go

Fixes #263
Ping @miekg @tianon

Fix definition lists that contain other lists

---

inline.go

This is purely a style change with no behavior difference.
In Go (unlike most other languages), `case` statements in a `switch` don't need an explicit `break` statement, it happens by default. Adding it explicitly is possible, but has no effect (if it's the last statement in the `case`).
In this case, having the `break` statement hurts readability because it's hard to tell if it's a mistake, and the `break` was intended to break out of the outer `for` loop, rather than do nothing for the `switch` statement. So, remove it, to make it more clear that there is no bug here.

Avoid unneeded break statement.

---

block.go
block_test.go

This was an unintended typo/mistake in #280.
This is stricter, and it's fine. The opening fence line will always need to have a newline.
Add another test for `isFenceLine`.

Make newline mandatory for opening fence line.

---

inline.go
latex.go
markdown.go

The constants are only used in the parsing phase, they are not recorded
in the AST directly, so make them private. Improve their names along the
way. Fix tagLength to return two values instead of taking an output
parameter.

Unpublish and rename LinkType constants

---

ref_test.go

Currently v2 is ~2.7x slower than v1. I have a bunch of optimizations of varying stages of hackiness on my box that (currently) bring it down to ~1.3x slower. I'm planning to push those changes to a separate optimizations branch bit by bit. So I want to get this benchmark landed on v2 before I branch off.

Repeat a run of reference tests under benchmark

---

block_test.go
html.go
markdown.go

Compare with #273 : this implementation is shorter, simpler, faster, easier to understand, and does not get in the way of other renderers.

v2: Move TOC generation to the HTML Renderer

---

html.go

Why not having an Icon parameter when we have CSS?
It's a nit that is certainly useful to many and comes at zero maintainance cost.

v2: Add Icon parameter to the HTML renderer

---

block.go
inline.go
markdown.go
node.go

Those functions are very similar to [Go's HTML package](https://godoc.org/golang.org/x/net/html), but the arguments differ: Go uses the parent while BF doesn't. I don't see a need for the parent, I find BF's way simpler. But Go developers aren't stupid, so there must be a good reason. If that reason happened to be relevant to Blackfriday, then we should make the same changes.
Comments?

v2: Export tree manipulation functions

---

helpers_test.go
html.go
inline_test.go
markdown.go
smartypants.go

Smartypants is HTML-specific.
There is no need to run Smartypants from `Render()`.
This simplifies extensions built upon the HTML renderer.

v2: Factor Smartypants to HTML

---

inline.go
markdown.go

The former hacks around maybeLineBreak and Smartypants are no longer
needed.
The algorithm has been streamlined: shorter, simpler, faster.
The 'currBlock' field of the parser is gone.
Bonus: A rough perf increase of 6-8%!

v2: Only split when inline callbacks consume some bytes

---

block.go

I ran into this while looking into a [bug in `markdownfmt`](https://github.com/shurcooL/markdownfmt/issues/30). I've realized I should really update to v2, and I promise to do that soon. However, this fix seems harmless and relatively easy to reason about. All current test are passing. I hope that's enough to merge it in.
I was going to write tests for this, but realized that it would be very very verbose. I'd have to create a mock implementation of a `blackfriday.Renderer`, then wrap it around a real renderer (because of the known limitation of parser/renderer of v1). But investing more into v1 doesn't make much sense.
The implementation details are the commit message, pasted here for convenience:
> The `LIST_ITEM_END_OF_LIST` flag is an internal flag passed to renderers when rendering …

v1: Set LIST_ITEM_END_OF_LIST when list is at end of document.

---

block.go
html.go
inline_test.go
markdown.go
node.go

Clean up footnotes part of an AST: don't force HTML-specific pieces there, just keep a clean list of footnotes. Since some renderers might want to process footnotes differently, let them know about footnotes by having a flag on that list.

v2: move footnotes to html

---

node.go

When passed a non-container root node, the former algorithm would go on
walking down the rest of the tree beyond the root.
The former walk fix was supposed to do that but somehow the code
disappeared in the process.

v2: Fix walk with non-container root nodes

---

html.go
inline_test.go

It's been broken since early 2014, which clearly demonstrates that
nobody uses it.
Fixes #252.

Ditch SkipStyle flag

---

README.md
block.go
block_test.go
html.go
markdown.go
node.go

I've left test cases alone since can't lean on the compiler for
crosschecking there.
Fixes #330.

Fix all headings wrongly referred to as headers

---

inline_test.go
markdown.go

The check was introduced with d28de22, when fixing #172 and #173.
Then I removed it with bcd6dd8 when fixing #180
And then it was reintroduced with 232d06c when fixing regression.
It seems that the check can be removed again. All these cases now have
tests (including the one from 69f51af, which seems to have landed to v1
only, copying it here) and they all pass.
(As discussed in #311, where it was rediscovered)

Fix #180 again

---

block.go
block_test.go
helpers_test.go
inline.go
inline_test.go
markdown.go
ref_test.go

Convert the most important Blackfriday's function, `Markdown()`, to accept functional options (as per this Dave Cheney's post: https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis)
This dawned on me a bit late in the cycle, but thankfully just in time before we announce v2 with full lungs.
In essence, here's the main benefit: instead of calling `blackfriday.MarkdownCommon(input)`, you can now call `blackfriday.Markdown(input)`.
Instead of `blackfriday.MarkdownBasic(input)`, call `blackfriday.Markdown(input, WithNoExtensions())`.
And for a fully customized version:
``` go
blackfriday.Markdown(input, blackfriday.WithRefOverride(override), blackfriday.WithExtensions(exts), blackfriday.WithRenderer(yourRenderer))
```
I am also very tempted to take this chance to change the …

Change the public interface to use functional options

---

inline.go
inline_test.go
markdown.go

Fix the infinite loop when there is a self-refer footnote by checking if
the reference is already added into parser.notes.
It also fixes of creating duplicate footnotes through this modification.
Add coresponding testcase.

fix duplicate and recursive footnotes. (#241)

---

README.md
block_test.go
html.go
markdown.go

Improve Renderer to be less confusing. Fix documentation for it.
OmitContents flag got dropped along the way. First, it would fit poorly
into the new design and second, it's unclear how widely this feature is
used. But most importantly, it's trivial to roll your own with the v2
API: https://gist.github.com/rtfb/2693f6bfcc1760661e8d2fb832763a15
Fixes #368.

v2: improve Renderer and fix #368

---

html.go
inline_test.go
smartypants.go

This commits adds flag `HTML_SMARTYPANTS_QUOTES_NBSP` which, when combined with `HTML_USE_SMARTYPANTS` will insert non-breaking spaces between the double quotes and the contained text.
This is mostly relevant for use in French  with `HTML_SMARTYPANTS_ANGLED_QUOTES`.
It should not hurt existing code path in the performance department:
```
name                     old time/op    new time/op    delta
SmartDoubleQuotes-4    2.58µs ± 1%    2.58µs ± 1%   ~             (p=1.000 n=5+5)
name                     old alloc/op   new alloc/op   delta
SmartDoubleQuotes-4    5.27kB ± 0%    5.27kB ± 0%   ~     (all samples are equal)
name                     old allocs/op  new allocs/op  delta
SmartDoubleQuotes-4      13.0 ± 0%      13.0 ± 0%   ~     (all samples are equal)
```
Fixes #378

Add Smartypants support for French Guillemets

---

html.go

They were cluttering the documentation and are not useful otherwise.

Unexport a bunch of constants private to HTML renderer

---

README.md

Should also merge this commit over to v2.

Fix broken link to v2 in README

---

html.go
inline_test.go

As noted on #336, footnotes generate invalid HTML5 - validator.w3.org objects.
This change simply removes the (now) invalid `rel="footnote"`, and updates the tests. They all pass.
Thanks for this project - I'm using it with Hugo, so this change targets the older version. The same issue with different code is in v2. I'm happy to make a similar change there if needed.
EDIT: Travis CI builds against some go versions fail, others pass. The failures are due to breaching a 10 minute deadline, they happen on current master, and are not caused or made worse by this change.

Fix HTML5 by removing rel="footnote" which is invalid.

---

html.go
inline_test.go

See #433 for an equivalent change on v1 branch.
@rtfb - change for v2 as discussed. Any problems, let me know.

v2: Fix HTML5 by removing rel="footnote" which is invalid.

---

block.go
block_test.go

```
1. hello
2. world
* goodbye
* world
```
now produces two lists:
1. hello
2. world
* goodbye
* world
instead of:
1. hello
2. world
3. goodbye
4. world

Fix consecutive lists of different kinds

---

README.md

I created confluence wiki renderer for the Blackfriday v2. It would be great if you can add this renderer to README.md.

Add a reference for confluence wiki renderer in the README.md.

---

block.go
block_test.go
html.go
latex.go
markdown.go

According to the common mark standard, code fence info strings can be anything,
not just single words. Update the tests and parser accordingly.
The formatter already expected an info string with a language and HTML classes,
so this does not need to change. Update the LaTeX formatter to take the first
word of the info string as the language.
Fixes #410 (in v1).

Accept info strings in code fences

---

block.go
block_test.go
markdown.go

According to common mark, the info string for a fenced code block can be any
non-whitespace string, so adjust the code to read a full string instead of
just the syntax name.
Fixes #410 in v2.

Add full info string in fenced code blocks

---

block.go
block_test.go

Fix for issue russross/blackfriday#239
This appears to also work in V1, although this PR is for V2
The following would confuse the `- codeline` as if it were a start of a nested list.
```
- line
```
- codeline
```
```
The PR checks if a code fence is found, and don't use code to figure out if a list item has ended.
a code review is most welcome as I'm sure I'm missing something.
thanks!
n

Fix for issue russross/blackfriday#239

---

inline.go

The old regex missed a lot of HTML entities, like long references (from 6-character entites like `&approx;` to the somewhat rarer `&CounterClockwiseContourIntegral;`) as well as numeric references (decimal e.g. `&#1234;` or hex e.g. `&#x13AF6;`). This fixes that.

Fixed HTML entity regex

---

block_test.go
html.go

Setting HTMLRendererParameters.HeadingLevelOffset to L changes
default HTML heading levels from hX to h(X+L).

Add heading offset option to HTML renderer

---

html.go
inline_test.go

I think it is necessary to force rel="noopener" into the external links, even if there are other libraries such as bluemonday can do it.
The reason, blackfriday can formatting and displaying untrusted user data, but if the data is confirmed safe, it's unnecessary to sanitize data with bluemonday, and we still need to add rel="noopener" to keep site safe.
rel="noopener" is not about data, it's about **site** safe and **the style of links**. or, in other words, force rel="noopener" into the external links is the same as force target="_blank".
Why we discriminate "noopener"? Just because it is related to safe?

add NoopenerLinks

---

README.md

Chroma is a general purpose code highlighting library, and bfchroma
provides an easy to use glue layer for Blackfriday to interface with
Chroma.
Fixes #10.

Add a link to bfchroma, glue library with Chroma

---

block.go
block_test.go

This is the fix for https://github.com/russross/blackfriday/issues/239 from @client9 and myself.
Sent a message in https://github.com/russross/blackfriday/issues/239 outlining the issues client9 faced with the tests and the fixes I made.

Fix block parsing for fenced code blocks in lists

---

go.mod

Note that I have no practical experience with Go Modules and major versions, but this should be correct according to https://github.com/golang/go/wiki/Modules
I will follow up with a PR for the master branch.
I would also appreciate if this could be followed by a version tag. I plan to finally get to the Blackfriday v2 upgrade in Hugo in the near future ...

v2: Add go.mod

---

inline.go
testdata/Links, inline style.html
testdata/Links, inline style.text

Fix #510.
By using `isBackslashEscaped`, it prevents incorrect interpretation of backslash in link.

Fix checking of backslash in link text (#510)

---

README.md

It's more consistent and it's possible to mark code blocks with "go" hint,
so we get syntax highlighting on GitHub.

readme: use fenced code blocks

---

go.mod
go.sum
helpers_test.go

This removes the testing dependency on [`github.com/pmezard/go-difflib`](https://godoc.org/github.com/pmezard/go-difflib/difflib) which, per the [README](https://github.com/pmezard/go-difflib/blob/master/README.md), is no longer maintained.
I did not try to match the diff output exactly, assuming these weren't actual patches being applied somewhere, but the relevant information is still included.
A failing test now looks like this:
```
blackfriday (v2 *=) $ go test
--- FAIL: TestReference_EXTENSION_NO_EMPTY_LINE_BEFORE_BLOCK (8.09s)
helpers_test.go:173:
file: Amps and angle encoding
line: 6
-<p>4 &lt; 6.</p>
+<p>4 &lt; 5.</p>
line: 16
-<p>Here's an inline <a href="/script?foo=1&amp;bar=2">link</a></p>
+<p>Here's an inline <a href="/script?foo=1&amp;bar=2">link</a>.</p>
--- FAIL: …
```

Remove dep on umaintained difflib

---

node.go

These functions are very useful for applications that walk the AST generated by `blackfriday`. Without these exports, the applications have to work out which are leaf nodes and which are container nodes themselves.

Export Node.IsContainer and add Node.IsLeaf

---

html.go
inline_test.go

Backport noopener links to v1

---

html.go

This changes the default `params.FootnoteReturnLinkContents` from `<sup>[return]</sup>` to `<span aria-label='Return'>↩\ufe0e</span>`.
It’s very common to use `↩` in footnote links. However, some platforms like iOS and iPadOS choose to use emoji presentation for this particular character. This leads to lots of blogs, by default, looking silly on portable Apple gizmos, as described in <https://github.com/jgm/pandoc/issues/5469>. By switching to a return arrow with a disable-emojification variation selector, we get blackfriday to do the right thing by default.
Additionally, ↩ is more language-agnostic than “return” is, so blackfriday will work better out of the box for more people.

Use ↩ as default params.FootnoteReturnLinkContents

---

go.mod

This is a result of running `go mod tidy` using go 1.13.6.
In my devel toolchain (vim-go -> gopls -> go 1.13), go apparently
wants to add this line to go.mod, but since the modules are read-only,
it fails, which leads to gopls failing, too.
Merging this and tagging a release would help tremendously
(not because of this PR per se, but mostly because of
https://github.com/russross/blackfriday/pull/509 and https://github.com/russross/blackfriday/pull/515 
which are not in a released version yet).
@russross @rtfb @SamWhited PTAL

go.mod: add go version
