- html.go
- inline.go
- inline_test.go
when link to current directory or parent directory
> update about links

- markdown.go
Add checking before accessing the input data.
Fix #172 and #173 issues.
Signed-off-by: Tw <tw19881113@gmail.com>
> fix index out of range panic in reference link

- block.go
- block_test.go
Hi,
I discovered an issue with my latest PR in a case which wasn't tested by the unit tests. This PR implements the fix and adds the missing test cases.
Regards,
> Fix definition lists end-of-list detection

- README.md
'Definition lists' and 'Footnotes' are not documented.
> README: Add 'Definition lists' and 'Footnotes'

- block_test.go
This is a PR into branch `issue-122`, not `master`.
Addresses https://github.com/russross/blackfriday/pull/211/files#r43576434.
> Make test values more readable, add additional test cases.

- inline.go
- inline_test.go
Fixes #116. Most code originally by @miekg.
> Allow parentheses inside of links

- block.go
- block_test.go
- inline.go
> Implement support for CDATA section

- block.go
- block_test.go
- inline_test.go
- markdown.go
- markdown_test.go
- ref_test.go
See commit messages for details. Highly recommended to review commit-by-commit rather than entire diff at once.
> Fix fenced code block rendering with content resembling references.

- block.go
- block_test.go
- helpers_test.go
- markdown.go
- markdown_test.go
Forwardport changes from #280.
Fixes #279 (for v2).
There were some merge conflicts/differences to resolve, but overall not too bad.
> v2: Fix issue in fenced code block pre-processing.

- block.go
- block_test.go
- helpers_test.go
- html.go
- inline.go
- latex.go
- markdown.go
- node.go
- smartypants.go
Since on of the things lint complains about are docstrings, documentation got somewhat improved.
> Fix most of lint errors on v2

- node.go
When passed a non-container root node, or when the visitor whould return
SkipChildren for the root node, the former algorithm would go on walking
down the rest of the tree beyond the root.
This commit also removes unneeded functions and variables.
> v2: Fix walk so that it does not step outside the root node

- doc.go
- markdown.go
Plus elaborate the documentation a bit.
> v2: Extract package level documentation to doc.go

- .travis.yml
So that we could have a historic record of performance.
> v2: Run the reference benchmark on Travis

- inline.go
- markdown.go
- node.go
As per discussion in #302, this adds a pointer to footnote nodes from the referring Node, in the LinkData payload.
> V2 add links to footnotes

- README.md
> README: Update URL of LaTeX renderer.

- markdown.go
> Fix comment about inline footnotes

- helpers_test.go
> Print diffs for reference tests

- block_test.go
- esc_test.go
- inline_test.go
- markdown_test.go
- ref_test.go
> Run tests in parallel

- block.go
This sets the fenceLength in fenced code block nodes.
> block.go: set fenceLength

- README.md
Hi!
For a recent project i needed to convert gitlab markdown messages into slack message style.
I found the Blackfriday parser and thought to honor this project I wanted to give something back to the community, and so I published the "slackdown" renderer.
Feedback is appreciated
> Add slack message style renderer

- inline.go
- testdata/Links, inline style.html
- testdata/Links, inline style.text
> Fix checking of backslash in link text for v1 (#510)

- markdown.go
> Add <details> to recognized HTML5 block tags
